### ISSUE TITLE
Code blocks from doxygen are not highlighted correctly

### ISSUE THREAD

**Issue by rweickelt** [michaeljones/breathe#123] opened 2014-09-01 08:31 UTC
Code blocks in doxygen are rendered as literal blocks without syntax highlighting. The reason is, that the doxygen XML output does not contain information about the used code domain. 

The example code

``` cpp
bool myFunction(int parameter)
{
    if (parameter > 0)
    {
        return false;
    }

    return true;
}
```

produces the following XML output

``` xml
<para><programlisting><codeline><highlight class="keywordtype">bool</highlight><highlight class="normal"><sp/>myFunction(</highlight><highlight class="keywordtype">int</highlight><highlight class="normal"><sp/>parameter)</highlight></codeline>
<codeline><highlight class="normal">{</highlight></codeline>
<codeline><highlight class="normal"><sp/><sp/><sp/><sp/></highlight><highlight class="keywordflow">if</highlight><highlight class="normal"><sp/>(parameter<sp/>&gt;<sp/>0)</highlight></codeline>
<codeline><highlight class="normal"><sp/><sp/><sp/><sp/>{</highlight></codeline>
<codeline><highlight class="normal"><sp/><sp/><sp/><sp/><sp/><sp/><sp/><sp/></highlight><highlight class="keywordflow">return</highlight><highlight class="normal"><sp/></highlight><highlight class="keyword">false</highlight><highlight class="normal">;</highlight></codeline>
<codeline><highlight class="normal"><sp/><sp/><sp/><sp/>}</highlight></codeline>
<codeline><highlight class="normal"></highlight></codeline>
<codeline><highlight class="normal"><sp/><sp/><sp/><sp/></highlight><highlight class="keywordflow">return</highlight><highlight class="normal"><sp/></highlight><highlight class="keyword">true</highlight><highlight class="normal">;</highlight></codeline>
<codeline><highlight class="normal">}</highlight></codeline>
</programlisting></para>
```

The problem could be probably solved by using embedded rst but at the price of not having links to documented items.

**Comment by mosra** [comment] 2017-11-19 13:53
Hi all, hope it's okay that I revived this old issue :)

I just submited a patch to Doxygen that propagates language information to all `<programlisting>` elements in XML files and I think that might help you here: https://github.com/doxygen/doxygen/pull/621

In my own Doxygen theme I'm just removing all Doxygen-made highlighting in those blocks and passing the raw code + language info through Pygments to get proper highlighting. For anyone who's interested, here's a screenshot and link to live snapshot: https://twitter.com/czmosra/status/932068062693642242

**Comment by SylvainCorlay** [comment] 2017-11-20 22:26
@mosra thanks for the update. I think that it is especially important when documenting things such as language bindings etc...

I don't know how much time it will take for doxygen to be released with your patch.

Although there might be some hope:

 - readthedocs supports conda (a general-purpose package manager)
 - doxygen is packaged for conda (on the conda-forge channel)

We use conda-forge + breathe for the documentation of e.g. xtensor.

So I can probably make a new build of the doxygen conda-package including your patch, and we could use it with breathe.

**Comment by melvinvermeeren** [comment] 2018-06-02 20:54
I think it is safe to say that @mosra 's patch is in current Doxygen releases. Based upon reading the above is it safe to say that Breathe still needs to implement reading the additional XML and use it for rendering?

**Comment by 2bndy5** [comment] 2021-11-08 03:00
+1 to this. It would be very helpful to feed the code-block's domain into sphinx.

For example, I have a project that documents the C++ implementation, but it is littered with relative python wrapper "gotcha" example code-blocks to note slight differences in buffer object usages. Currently, I get a warning (related to this issue) for every python snippet in the C++ docs.

**Comment by jakobandersen** [comment] 2021-11-08 16:56
@2bndy5, would it be possible for you (or someone else) to make a small example project to start discussion from? so we are aligned on what this feature request is about.

**Comment by 2bndy5** [comment] 2021-11-08 17:04
After posting that comment, I tried to reproduce the warnings in a simple example project, but I was unable to do so. It seems that pygments is raising warnings for highly terse code-blocks.

I also looked at the XML output for a few `programlisting` tags, and I didn't see any obvious indication of the domain related to them. So, I'm not sure what help [the mentioned & merged PR to doxygen](https://github.com/doxygen/doxygen/pull/621) can bring to this issue.

**Comment by jakobandersen** [comment] 2021-11-08 17:38
With a bit of poking around in Breathe and Sphinx I think what is needed is:
1. Get the ``filename`` attribute from the Doxygen XML parsed.
2. In ``visit_listing`` https://github.com/michaeljones/breathe/blob/aec47028e05ad8d77e960db9d25140e9fd1c0127/breathe/renderer/sphinxrenderer.py#L1595, covert that attribute into a language name that the Sphinx  ``code-block`` directive would accept and set it as the ``language`` attribute on the ``literal_block`` node, a la Sphinx: https://github.com/sphinx-doc/sphinx/blob/6c6cc8a6f50b18331cb818160d168d7bb9c03e55/sphinx/directives/code.py#L152
3. Instead of setting child nodes of the ``literal_block`` node, stringify it and set it as the first two arguments, like in the Sphinx ``code-blcok`` directive implementation (https://github.com/sphinx-doc/sphinx/blob/6c6cc8a6f50b18331cb818160d168d7bb9c03e55/sphinx/directives/code.py#L145)

**Comment by 2bndy5** [comment] 2021-11-08 17:49
I would be happier if doxygen would output the domain of a code-block as the `programlisting` tag attribute. Now, the link you mentioned also deals with line numbers. It would also be a lot easier if that flag was also an attribute. My intention here is to more easily translate the doxygen `@code` cmd's args into sphinx directive args (including doxygen default arg values) as they are almost identical (sphinx is better - naturally).

My use case wouldn't be solved by your proposed step 1 & 2 because I'm putting python code-blocks in a document created from a C++ header file.

**Comment by jakobandersen** [comment] 2021-11-08 18:03
> I would be happier if doxygen would output the domain of a code-block as the `programlisting` tag attribute.

For me it does that. E.g., with ``test.hpp`` having
```c++
/// 
/// Something
/// \code{blah}
/// int main() {}
/// \endcode
/// something else
void f();
```
I get the Doxygen XML
```xml
        <detaileddescription>
<para>Something <programlisting filename=".blah"><codeline><highlight class="normal">int<sp/>main()<sp/>{}</highlight></codeline>
</programlisting> something else </para>
        </detaileddescription>
```
It seems that whatever is in {...} after the ``\code`` becomes a file extension-like "filename".

> Now, the link you mentioned also deals with line numbers. It would also be a lot easier if that flag was also an attribute.

All the line number stuff for ``code-block`` is optional, so we can safely ignore it.

> My use case wouldn't be solved by your proposed step 1 & 2 because I'm putting python code-blocks in a document created from a C++ header file.

Hmm, it seems to me that individual ``\code`` commands can have whichever language you like. Or am I misunderstanding your situation?

**Comment by 2bndy5** [comment] 2021-11-08 18:06
>Hmm, it seems to me that individual \code commands can have whichever language you like. Or am I misunderstanding your situation?

exactly correct.

I never noticed the `filename` attribute. That could very well be used to specify the highlighing language used for pygments! I'll look into that more.

**Comment by 2bndy5** [comment] 2021-11-08 18:33
I see that the `filename` attribute is only shown when it is specified by the docs' author. Sorry if I'm repeating what you already know; I'm just catching up...

**Comment by 2bndy5** [comment] 2021-11-08 18:45
https://github.com/michaeljones/breathe/blob/aec47028e05ad8d77e960db9d25140e9fd1c0127/breathe/parser/compound.py#L992-L998

I found an archive of the dead link in this comment:
https://web.archive.org/web/20141029134852/https://www.stack.nl/~dimitri/doxygen/manual/examples/include/html/example.html
But I fail to understand the rationality in the comment.

**Comment by 2bndy5** [comment] 2021-11-08 21:41
What I've tried so far:
1. ```py
   # in compoundsuper.py
   # in listingType class
    def buildAttributes(self, attrs: minidom.NamedNodeMap):
        if "filename" in attrs.keys():
            # extract the domain for this programlisting tag.
            ext_tuple = os.path.splitext(attrs["filename"].value)
            self.domain = ext_tuple[0 if not ext_tuple[1] else 1].lstrip(".")
   ```
2. ```py
   # in sphinxrenderer.py
    def visit_listing(self, node) -> List[Node]:
        nodelist = []  # type: List[Node]
        for i, item in enumerate(node.codeline):
            # Put new lines between the lines. There must be a more pythonic way of doing this
            if i:
                nodelist.append(nodes.Text("\n"))
            nodelist.extend(self.render(item))
        code = "".join([x.astext() for x in nodelist])

        block = nodes.literal_block(code, code)
        if node.domain:
            block["langauge"] = node.domain
        return [block]
    ```

Unfortunately, these changes don't seem to render any differently. All code-blocks still respect whatever the `highlight` language is specified (or the `highlight_language` config option). I'll keep digging, but I feel like I'm missing something not-so-obvious...

**Comment by 2bndy5** [comment] 2021-11-08 22:02
# 🤣 
fixing this typo solved it
> ```py
>       block["langauge"] = node.domain
> ```

Ironlically, language is spelled wrong 🤣

**Comment by 2bndy5** [comment] 2021-11-08 22:18
@jakobandersen I'm ready to submit your proposed implementation. Should make any other considerations? Would breathe's `ProjectInfo.domain_for_file()` apply to this scenario?

**Comment by 2bndy5** [comment] 2021-11-09 11:22
I've added a bit that passes the `compounddef` tag's `language` attribute to the modified `listingType` c'tor. This should only affect `programlisting` tags that are discovered as direct children of a `compoundddef`. Ultimately, this little bit won't ever get used until someone tries to hack together a viewsource-type feature in breathe (yes, I have been looking into that).

**Comment by mosra** [comment] 2021-11-11 11:06
> I see that the `filename` attribute is only shown when it is specified by the docs' author

Just FYI, it also gets specified when you use Doxygen's `@include` or `@snippet` commands (which I use quite often to have documentation snippets [checked by the compiler](https://github.com/mosra/magnum/blob/master/doc/snippets/MagnumMath.cpp)), and that was the main reason behind the Doxygen PR I linked above.

**Comment by 2bndy5** [comment] 2021-11-11 15:39
@mosra Interesting advice! I re-read the PR you submitted to doxygen, with my newly enlightened understanding, and I took your advice about using pygments to guess the lexer name from the full filename. Thanks for submitting that PR!

**Closed** 2022-02-09 21:06 UTC
