### ISSUE TITLE
breathe-Derivatives not working for global members.

### ISSUE THREAD

**Issue by Krishna2126** [michaeljones/breathe#423] opened 2019-03-05 05:36 UTC
how can work on the global members which are not present in header file.
need solution for that
i tried all the combination of EXTRACT_* still it is not taking global function which are not in header.
```
Example:

Header:
int NvIspSettingsTest2();
static int NvIspSettingsTest3();

.cpp:
// doesn't work
static int NvIspSettingsTest()
{
return 1;
}

// works
extern "C" int NvIspSettingsTest2()
{
return 1;
}

// works
static int NvIspSettingsTest3()
{
return 1;
}

// works
namespace statictest {
static int NvIspSettingsTest4()
{
return 1;
}
}
```
So it seems that things fail only if
• The function is in global namespace
• And it is not declared in a header

in doxygen HTML it is displaying but not in breathe.
i think it might be a breathe issue.

**Comment by melvinvermeeren** [comment] 2019-03-14 22:29
Appears to be a duplicate of #414, just posted a comment there. Closing this one.

**Closed by melvinvermeeren** 2019-03-14 22:29 UTC
Labels: duplicate
