### ISSUE TITLE
Crash when using a name for member group

### ISSUE THREAD

**Issue by pwm1234** [michaeljones/breathe#211] opened 2015-07-08 21:29 UTC
I encountered this error when naming a member group. Unfortunately, I was unable to reproduce the error with your example documentation. My hack was to replace line 95 of __init_.py with

```
    try:
        if not self.filter_.allow(context.node_stack):
            return NullRenderer()
    except AttributeError as e:
        return NullRenderer()
```

But I doubt a simple swallowing of the exception is a good solution.

Below is the traceback. 

```
# Loaded extensions:
#   breathe (unknown version) from C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\breathe-4.0.0-py2.7.egg\breathe\__init__.pyc
#   sphinx.ext.autodoc (1.3.1) from C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\sphinx\ext\autodoc.pyc
#   sphinx.ext.intersphinx (1.3.1) from C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\sphinx\ext\intersphinx.pyc
#   sphinx.ext.doctest (1.3.1) from C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\sphinx\ext\doctest.pyc
#   sphinx.ext.mathjax (1.3.1) from C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\sphinx\ext\mathjax.pyc
#   numpydoc (unknown version) from C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\numpydoc-0.6.dev0-py2.7.egg\numpydoc\__init__.pyc
#   sphinx.ext.viewcode (1.3.1) from C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\sphinx\ext\viewcode.pyc
#   sphinx.ext.ifconfig (1.3.1) from C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\sphinx\ext\ifconfig.pyc
#   alabaster (0.7.3) from C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\alabaster\__init__.pyc
#   sphinxcontrib.doxylink (unknown version) from C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\sphinxcontrib_doxylink-1.3-py2.7.egg\sphinxcontrib\doxylink\__init__.pyc
#   sphinx.ext.autosummary (1.3.1) from C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\sphinx\ext\autosummary\__init__.pyc
#   sphinx.ext.todo (1.3.1) from C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\sphinx\ext\todo.pyc
Traceback (most recent call last):
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\sphinx\cmdline.py", line 245, in main
    app.build(opts.force_all, filenames)
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\sphinx\application.py", line 264, in build
    self.builder.build_update()
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\sphinx\builders\__init__.py", line 245, in build_update
    'out of date' % len(to_build))
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\sphinx\builders\__init__.py", line 259, in build
    self.doctreedir, self.app))
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\sphinx\environment.py", line 618, in update
    self._read_serial(docnames, app)
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\sphinx\environment.py", line 638, in _read_serial
    self.read_doc(docname, app)
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\sphinx\environment.py", line 791, in read_doc
    pub.publish()
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\docutils\core.py", line 217, in publish
    self.settings)
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\sphinx\environment.py", line 126, in read
    self.parse()
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\docutils\readers\__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\docutils\parsers\rst\__init__.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\docutils\parsers\rst\states.py", line 170, in run
    input_source=document['source'])
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\docutils\parsers\rst\states.py", line 2961, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\docutils\parsers\rst\states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\docutils\parsers\rst\states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\docutils\parsers\rst\states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\docutils\parsers\rst\states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\docutils\parsers\rst\states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\docutils\parsers\rst\states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\docutils\parsers\rst\states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\docutils\parsers\rst\states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\docutils\parsers\rst\states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\docutils\parsers\rst\states.py", line 2299, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\docutils\parsers\rst\states.py", line 2311, in explicit_construct
    return method(self, expmatch)
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\docutils\parsers\rst\states.py", line 2054, in directive
    directive_class, match, type_name, option_presets)
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\docutils\parsers\rst\states.py", line 2103, in run_directive
    result = directive_instance.run()
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\breathe-4.0.0-py2.7.egg\breathe\directives.py", line 323, in run
    mask_factory)
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\breathe-4.0.0-py2.7.egg\breathe\directive\base.py", line 88, in render
    return object_renderer.render()
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\breathe-4.0.0-py2.7.egg\breathe\renderer\rst\doxygen\index.py", line 63, in render
    rendered_data = data_renderer.render()
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\breathe-4.0.0-py2.7.egg\breathe\renderer\rst\doxygen\compound.py", line 13, in render
    return compound_renderer.render()
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\breathe-4.0.0-py2.7.egg\breathe\renderer\rst\doxygen\compound.py", line 80, in render
    child_nodes = renderer.render()
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\breathe-4.0.0-py2.7.egg\breathe\renderer\rst\doxygen\compound.py", line 123, in render
    renderer = self.renderer_factory.create_renderer(context)
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\breathe-4.0.0-py2.7.egg\breathe\renderer\rst\doxygen\__init__.py", line 95, in create_renderer
    if not self.filter_.allow(context.node_stack):
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\breathe-4.0.0-py2.7.egg\breathe\renderer\rst\doxygen\filter.py", line 523, in allow
    if not filter_.allow(node_stack):
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\breathe-4.0.0-py2.7.egg\breathe\renderer\rst\doxygen\filter.py", line 540, in allow
    if filter_.allow(node_stack):
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\breathe-4.0.0-py2.7.egg\breathe\renderer\rst\doxygen\filter.py", line 523, in allow
    if not filter_.allow(node_stack):
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\breathe-4.0.0-py2.7.egg\breathe\renderer\rst\doxygen\filter.py", line 540, in allow
    if filter_.allow(node_stack):
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\breathe-4.0.0-py2.7.egg\breathe\renderer\rst\doxygen\filter.py", line 540, in allow
    if filter_.allow(node_stack):
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\breathe-4.0.0-py2.7.egg\breathe\renderer\rst\doxygen\filter.py", line 540, in allow
    if filter_.allow(node_stack):
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\breathe-4.0.0-py2.7.egg\breathe\renderer\rst\doxygen\filter.py", line 523, in allow
    if not filter_.allow(node_stack):
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\breathe-4.0.0-py2.7.egg\breathe\renderer\rst\doxygen\filter.py", line 422, in allow
    name = self.accessor(node_stack)
  File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\breathe-4.0.0-py2.7.egg\breathe\renderer\rst\doxygen\filter.py", line 341, in __call__
    return getattr(self.selector(node_stack), self.attribute_name)
AttributeError: descriptionTypeSub instance has no attribute 'name'
```

**Comment by michaeljones** [comment] 2015-07-09 19:08
Hi @pwm1234, thanks for reporting it. Sorry you couldn't reproduce it in the Breathe docs but thank you very much for trying. We'll try to take a look and see if we can figure out what is going on. If there is any information at all that you could provide it might help. 

Perhaps you might be able to print the value of `node_stack` at the time of the exception? `sphinx-build` has a `-P` flag for dropping into the debugger on an exception.

If possible it would also be great to know if it is happening with the latest code from github. There have been a few changes since the last release. If it has been fixed by chance then we'll happily cut another release.

Thanks again!

**Comment by michaeljones** [comment] 2015-07-09 19:20
Or we can just do a release and then you can test with that? Might be easier unless you're happy installing from github.

**Comment by pwm1234** [comment] 2015-07-09 20:12
Hi Michael, I am fine using the source from github--in fact I already am! (Sorry, I should have mentioned that. I am using master at git commit a804015c1baadb818a6a1062619c3e305feaca05 from 6/29.)

Here is the debugger output when I use ``-P`` and ``print node_stack``

      File "C:\Users\pmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\breathe-4.0.0-py2.7.egg\breathe\renderer\rst\doxygen\filter.py", line 341, in __call__
        return getattr(self.selector(node_stack), self.attribute_name)
    AttributeError: descriptionTypeSub instance has no attribute 'name'
    > c:\users\pmiller\appdata\local\enthought\canopy\user\lib\site-packages\breathe-4.0.0-py2.7.egg\breathe\renderer\rst\doxygen\filter.py(341)__call__()
    -> return getattr(self.selector(node_stack), self.attribute_name)
    (Pdb) print node_stack
    [<breathe.parser.doxygen.compound.descriptionTypeSub instance at 0x0000000005F651C8>,
     <breathe.parser.doxygen.compound.sectiondefTypeSub instance at 0x0000000005F65088>,
     <breathe.parser.doxygen.compound.compounddefTypeSub instance at 0x0000000005F62BC8>,
     <breathe.parser.doxygen.compound.DoxygenTypeSub instance at 0x0000000005CB56C8>,
     <breathe.parser.doxygen.index.CompoundTypeSub instance at 0x0000000005B131C8>,
     <breathe.parser.doxygen.index.DoxygenTypeSub instance at 0x00000000059D3688>,
     <breathe.finder.core.FakeParentNode object at 0x0000000007C239B0>]
    (Pdb) print self.attribute_name
    name

**Comment by michaeljones** [comment] 2015-07-09 20:49
Thanks for the quick response. Kind of you to provide the information. I guess I was confused by the stack trace which includes `breathe-4.0.0` but I guess you can install from github and provide a version number? Or does it pick up the latest tag name?

**Comment by pwm1234** [comment] 2015-07-10 04:09
I am not sure why it says breathe-4.0.0. All I have done is clone the repo from github, then `python setup.py install` it (on my windows computer). I do this everytime I make a change. (I guess putting the module directory in my PYTHONPATH is faster/better, but I do not make that many changes, so this works for me right now.)

**Comment by michaeljones** [comment] 2015-07-10 08:35
No trouble. If you're installing it from the clone then it'll just pick up the version number in the `setup.py`. I'm probably just confused anyway. Wanted to check. Hoped it might have been fixed already :)

**Comment by melvinvermeeren** [comment] 2018-06-03 20:10
Because of the age of this bug I sort of assume it has been silently fixed by now.

@pwm1234 if you still experience this problem please leave a comment.

**Closed by melvinvermeeren** 2018-06-03 20:10 UTC
Labels: bug, code
