### ISSUE TITLE
doxygen parameter direction not in latex output

### ISSUE THREAD

**Issue by f-b-e** [michaeljones/breathe#269] opened 2016-07-04 13:51 UTC
Function parameter directions are not in the latex output.
Example:

``` c
/**
*  @param[out] dst Destination pointer.
*  @param[in] src Source pointer
*/
```

It would be great to have **in** or/and **out** present in the Latex output.
Thx

**Comment by michaeljones** [comment] 2016-09-30 10:45
Thanks for raising this. Sorry for the silence. We don't have a huge amount of development time on this project but we'd be very happy to help & review code if you get a chance to look into this.

**Comment by t-b** [comment] 2016-09-30 14:05
The issue is output independent.

A fix would probably read the direction attribute of the parameter from the XML.

```
<para><parameterlist kind="param"><parameteritem>
<parameternamelist>
<parametername direction="in">a</parametername>
</parameternamelist>
<parameterdescription>
<para>
```

From a coarse look into the code it looks like a fix would touch docParaTypeSub.buildChildren.

**Comment by f-b-e** [comment] 2016-09-30 14:46
Hi, thanks for the support.
I do it with a hack. I decorate the render function like this:

    from breathe.renderer.compound import DocParamNameSubRenderer
    def render_direction(render_func):
        """render decorator which adds parameter direction"""
        def render(self):
            nodes = render_func(self)
            if self.data_object.direction:
                nodes.append(self.node_factory.Text(
                    " [{direction}]".format(direction=self.data_object.direction)))
            return nodes
        return render
    DocParamNameSubRenderer.render = render_direction(DocParamNameSubRenderer.render)

**Comment by melvinvermeeren** [comment] 2018-06-02 22:00
The current version of Sphinx (1.7.5) + Breathe (4.9.0) may have solved this.

In they case they did not I think your hack could be merged if tidied up a bit and put in the appropriate place. If you could check if it's still a problem and if so submit a PR I would really appreciate it!

**Comment by t-b** [comment] 2018-06-03 11:10
@melvinvermeeren @f-b-e 

This is unfortunately not yet solved witht the latest versions. I'm looking at the HTML output.

I've a test repo here -> https://github.com/t-b/breathe-doxygen-filter-test, just execute `run.sh` and then `xdg-open source/html/output/file/test_8cpp.html`.
I've used breathe 4.9.0, sphinx 1.7.5 and doxygen master from today.

**Comment by melvinvermeeren** [comment] 2018-06-03 22:53
In that case the next step is to implement reading the XML tag and then render it properly. Thank you for the test project, it will be useful when implementing this.

As this is tagged as enhancement right now I cannot say when this will happen. For me personally the bugs have higher priority. And although I intend to maintain Breathe for a long time I am not certain if I can contribute to actual development enough to resolve all open issues since there so many of them.

Though with the code snippet above and the relative simplicity of the issue hopefully it will not be too long.

**Comment by fjolliton** [comment] 2019-04-11 12:44
With Sphinx 1.8.4 and Breathe 4.12.0 we use the following workaround (for HTML):

```
def patch_breathe():
    from breathe.parser.compoundsuper import docParamName, Node, MixedContainer
    orig = docParamName.buildChildren
    def buildChildren(self, child_, nodename_):
        orig(self, child_, nodename_)
        if child_.nodeType == Node.TEXT_NODE:
            d = child_.parentNode.attributes.get('direction')
            if d is not None:
                self.content_.insert(0, self.mixedclass_(MixedContainer.CategoryText,
                                                         MixedContainer.TypeNone,
                                                         '', f'[{d.value}] '))
    docParamName.buildChildren = buildChildren

patch_breathe()
```

**Comment by t-b** [comment] 2019-04-11 13:49
@fjolliton Does that break anything? It looks like this could just be fixed in breathe like that or?

**Comment by fjolliton** [comment] 2019-04-11 13:53
@t-b This is just extending the generation of the text for the parameter, so it is unlikely to break anything I think. But obviously this can break as soon as Breathe update its implementation. Patching Breathe would be better of course, but I don't have time to provide a PR regarding this.

**Comment by t-b** [comment] 2019-04-11 16:37
@fjolliton Thanks. I gave that a shot. I would like to use that without the hack myself ;)

**Closed** 2019-04-21 15:14 UTC
Labels: code, enhancement
