### ISSUE TITLE
Dashes at end of param line?

### ISSUE THREAD

**Issue by mikepurvis** [michaeljones/breathe#200] opened 2015-06-14 01:27 UTC
Example: http://breathe.readthedocs.org/en/latest/class.html#specific-members-example

![screen shot 2015-06-13 at 9 23 38 pm](https://cloud.githubusercontent.com/assets/944666/8146633/bf98cee6-1212-11e5-882c-fc7f2529782f.png)

What's the rationale for this dash being emitted? It would perhaps make sense if each parameter shared a line with its description, but with the description being enclosed in `<p></p>`, I think this dash should not be output.

**Comment by michaeljones** [comment] 2015-06-14 08:31
Thanks for raising it. Definitely looks less than ideal. There is a bit of history with parameters but it looks like they were left in a bad place. I'll try to address this.

Great to have another set of eyes pulling out these problems. Thanks!

**Comment by kratsg** [comment] 2015-11-04 22:58
:+1: I see this issue as well. When I do

```
@param var descr
```

I see a dash after `var` and then the next line contains `descr`.

**Comment by michaeljones** [comment] 2015-11-05 22:42
Thanks for highlighting this again. I clearly failed to get around to doing anything about it last time. I will try once more, hopefully with more success this time!

**Comment by rweickelt** [comment] 2016-11-07 17:25
So what's the state of this? Is the commit by olitheolix worth to merge?

**Comment by michaeljones** [comment] 2016-11-07 23:02
Ha, thanks for the prompt. I'm clearly terrible at this. Looks hopeful. I'll try to check it out properly by Wednesday at the latest. Please badger me before I forget for another year...

**Comment by michaeljones** [comment] 2016-11-09 19:09
I've updated #273. The current changes aren't ideal as they collapse paragraphs that we want to keep separate. Needs more investigation. I assume the problem is that doxygen places `para` tags inside parameter details and we need to essentially avoid rendering these as line breaking if we want to continue with the current format.

**Comment by melvinvermeeren** [comment] 2018-06-02 21:52
I will assume this is fixed by #285, first released as Breathe 4.4.0. If not please comment.

**Closed by melvinvermeeren** 2018-06-02 21:52 UTC
