### ISSUE TITLE
Breath for PHP source ?

### ISSUE THREAD

**Issue by buxx** [michaeljones/breathe#217] opened 2015-08-28 14:29 UTC
Hi,
I'm trying to use `breath` for php source code. It look like not working.

```
reading sources... [100%] index                                                                                                                                                    
/home/bsevajol/projects/tests/breathe-test/doc/source/index.rst:14: WARNING: Invalid definition: Expected identifier in nested name. [error at 5]
  Dog::$color
  -----^
/home/bsevajol/projects/tests/breathe-test/doc/source/index.rst:14: WARNING: Error when parsing function declaration:
If no return type {
Invalid definition: Expecting "," or ")" in parameters_and_qualifiers, got "$". [error at 18]
  Dog::getHello(Dog $dog)
  ------------------^
} else if return type {
If declId, parameters, and qualifiers {
Invalid definition: Expected identifier in nested name. [error at 13]
  Dog::getHello(Dog $dog)
  -------------^
} else If parenthesis in noptr-declarator {
Invalid definition: Expecting "(" in parameters_and_qualifiers. [error at 18]
  Dog::getHello(Dog $dog)
  ------------------^
}
}
looking for now-outdated files... none found
```

Breath work only with c++ ? Doxygen is not abstraction who permit to use any code documented with it ?

**Comment by michaeljones** [comment] 2015-10-25 14:03
Hi,

I'm really sorry that I've left this without a response for so long. Thank you for trying Breathe and for raising this issue.

Historically Breath has definitely had a C/C++ focus. Some of the behaviour at the moment kind of relies on that even more than it should perhaps. We've had requests from people looking to use it for Objective-C where is also fails to work properly but we haven't taken steps to properly support different languages yet.

Sorry about that! I am keen to see multi-language support properly implemented in Breathe but I am not able to spend much time on development at the moment. If you are keen to see this, I would welcome a pull request with some examples of php code that we could start working with.

Thanks again for raising the issue,
Michael

**Comment by lionpeloux** [comment] 2015-10-29 08:30
Hello Michael,

Very nice plugin here. I'm trying to set up a proper doc on RTD for one of my ongoing project on github, which is written in C#.

I've been struggling a bit to make it work on the RTD server but [this post](https://github.com/Cruel/readthedocs-breathe/tree/master/docs) was helpful to see how the doxyfile is configured with relative path, which is a bit hidden in your own doc. Maybe it could be a good idea to put a link to this on your doc ?!.

Anyway, I have to report the same kind of error as @buxx for every single parsed piece of code :
```
/home/docs/checkouts/readthedocs.org/user_builds/marsupilami/checkouts/latest/doc/manual/api.rst:99: WARNING: Error when parsing function declaration:
If no return type {
Invalid definition: Expecting "(" in parameters_and_qualifiers. [error at 9]
  abstract void Marsupilami.Kernel.DRElement.Update_LM(ref double LMt[][])
  ---------^
} else if return type {
Invalid definition: Expected identifier in nested name, got keyword: void [error at 13]
  abstract void Marsupilami.Kernel.DRElement.Update_LM(ref double LMt[][])
  -------------^
}

I would be happy to help resolve this, but I'm quite new to all this. If you could share some indications, I'll have a look at your code and try to submit a pull request.

Thanks,
Lionel

**Comment by lionpeloux** [comment] 2015-10-29 08:34
You could find my project and the RTD doc here :

- [Marsupilami - Repo](https://github.com/THINkSHELL/Marsupilami/tree/develop/doc/manual)
- [Marsupilami - RTD](http://marsupilami.readthedocs.org/en/latest/api.html#dynamic-relaxation-breathe)

And you can see the complete build warning msg here : [build msg](https://readthedocs.org/projects/marsupilami/builds/3438669/)

Lionel

**Comment by michaeljones** [comment] 2015-11-01 20:01
Hi Lionel,

Thanks for getting in touch and reporting the issue. And thanks for pointing out that project. Very happy to link to it and try to include more help in the Breathe documentation. We do have a section for 'Read the Docs' in the help [here](http://breathe.readthedocs.org/en/latest/readthedocs.html). It would be good to know what could be improved about it?

As for supporting C#, I'm not quite sure about the situation. We attempt to use the Sphinx domain handling code to parse some of the declarations and Sphinx doesn't support C# as a domain as far as I can tell from a quick check. Maybe there is an extension for it? If we can find one that we can use, that'd be great. If we can't find one then we should be able to output the details as we get them from doxygen without trying to get Sphinx to help us. That is how Breathe used to work. We'd still probably need better support for C# if the 'C/C++' style display doesn't quite fit that language.

I'm grateful for your offer of help. I'm going to need a bit of time to look into it before I can suggest where we might start fixing this.

Thanks again,
Michael

**Comment by melvinvermeeren** [comment] 2018-05-23 00:11
#351 added initial support for PHP and was merged recently. Although I didn't have doc to test with it with myself I suppose it should work. Closing this for now. Please comment if you have issues.

**Closed by melvinvermeeren** 2018-05-23 00:11 UTC

**Comment by RobertoRoos** [comment] 2021-02-02 08:56
Committing some necromancy here. I can't figure out how to use Breathe for PHP. I can't find it mentioned on https://breathe.readthedocs.io either.

I've created the following example repo: https://github.com/RobertoRoos/PHP-Breathe-Demo

When trying to build the docs I get the error:

> Generating XML output...
> Generating XML output for class MyPackage::Application
> Generating XML output for namespace MyPackage
> Generating XML output for file Application.php
> Generate XML output for dir /repo/src/
> Running dot...
> Running dot for graph 1/1
> lookup cache used 6/65536 hits=8 misses=6
> finished...
> building [mo]: targets for 0 po files that are out of date
> building [html]: targets for 3 source files that are out of date
> updating environment: [new config] 3 added, 0 changed, 0 removed
> reading sources... [ 33%] api
> reading sources... [ 66%] api/application
> 
> **Exception occurred:**
>   File "/usr/local/lib/python3.8/site-packages/breathe/renderer/sphinxrenderer.py", line 554, in run_directive
>     assert issubclass(type(directive), BaseObject)
> **AssertionError**

Is Breathe for PHP supposed to still be functional?
Thanks in advance.

**Comment by vermeeren** [comment] 2021-02-02 14:35
@RobertoRoos Back when PHP support was merged no tests or documentation were included, so it's very possible changes in the past years may have caused regressions. It is still more or less supported though maintainer/developer time is very scarce, patches are very welcome and will be handled.

A lot of the code sort of assumes C/C++ so the chance is very high all that is needed to make it work is some additional if statements if the style of `if php is not None and domain == 'php'`. If you have some time to test things out and make some changes that would be great. You can set and export `PYTHONPATH` to the path of a cloned Breathe repository for easy tweaking.

**Comment by RobertoRoos** [comment] 2021-02-02 14:44
Thank you for your reply!
I see, I might have a look to see if I can get anything out it.

I would much like this to work, considering the unique power ReadTheDocs as continuous documentation.

**Comment by kakenbok** [comment] 2021-02-04 09:48
```
.. doxygenclass:: MyPackage::Application
```

seems to be working

**Comment by RobertoRoos** [comment] 2021-02-04 18:20
Yeah, same here. It seems only the doxygenfile directive was broken. Thank you for pointing it out.
Regardless, the new pull request should be good addition.

**Comment by kakenbok** [comment] 2021-02-09 08:36
I also tried to use breathe with PHP, and I run into troubles in form of missing return types and stuff, and I got them running while downgrading breathe to 4.26.0 ... I suppose the recent development has been more focused on python or c language constructs and this seems to break with PHP. Since I also look for a JavaScript solution (and cannot find), I decided to not to try to autogen code documentation at all and manually write them for now.
