### ISSUE TITLE
Documentation does not compile properly (due to defined macros)

### ISSUE THREAD

**Issue by kratsg** [michaeljones/breathe#225] opened 2015-11-05 18:05 UTC
```
/Users/kratsg/xAODAnaHelpers/docs/JetHistsAlgo.rst:4: WARNING: Error when parsing function declaration:
If no return type {
Invalid definition: Expected identifier in nested name. [error at 37]
  JetHistsAlgo::ClassDef(JetHistsAlgo, 1)
  -------------------------------------^
} else if return type {
If declId, parameters, and qualifiers {
Invalid definition: Expected identifier in nested name. [error at 22]
  JetHistsAlgo::ClassDef(JetHistsAlgo, 1)
  ----------------------^
} else If parenthesis in noptr-declarator {
Invalid definition: Expecting "(" in parameters_and_qualifiers. [error at 35]
  JetHistsAlgo::ClassDef(JetHistsAlgo, 1)
  -----------------------------------^
}
}
/Users/kratsg/xAODAnaHelpers/docs/TrackHistsAlgo.rst:4: WARNING: Error when parsing function declaration:
If no return type {
Invalid definition: Expected identifier in nested name. [error at 41]
  TrackHistsAlgo::ClassDef(TrackHistsAlgo, 1)
  -----------------------------------------^
} else if return type {
If declId, parameters, and qualifiers {
Invalid definition: Expected identifier in nested name. [error at 24]
  TrackHistsAlgo::ClassDef(TrackHistsAlgo, 1)
  ------------------------^
} else If parenthesis in noptr-declarator {
Invalid definition: Expecting "(" in parameters_and_qualifiers. [error at 39]
  TrackHistsAlgo::ClassDef(TrackHistsAlgo, 1)
  ---------------------------------------^
}
}
```

you can see an example header file here: https://github.com/UCATLAS/xAODAnaHelpers/blob/master/xAODAnaHelpers/JetHistsAlgo.h

The macro is defined from ROOT. It looks like breathe doesn't strictly like it. The current solution is to do the following

``` c++
   /// @cond
   ClassDef(JetHistsAlgo, 1);
   /// @endcond
```

to make it work. The XML around this looks like

``` xml
<codeline lineno="48"><highlight class="normal"></highlight></codeline>
<codeline lineno="49"><highlight class="normal"><sp/><sp/></highlight><highlight class="comment">//<sp/>this<sp/>is<sp/>needed<sp/>to<sp/>distribute<sp/>the<sp/>algorithm<sp/>to<sp/>the<sp/>workers</highlight><highlight class="normal"></highlight></codeline>
<codeline lineno="50"><highlight class="normal"><sp/><sp/>ClassDef(<ref refid="class_jet_hists_algo" kindref="compound">JetHistsAlgo</ref>,<sp/>1);</highlight></codeline>
<codeline lineno="51"><highlight class="normal"></highlight></codeline>
<codeline lineno="52"><highlight class="normal">};</highlight></codeline>
<codeline lineno="53"><highlight class="normal"></highlight></codeline>
<codeline lineno="54"><highlight class="normal"></highlight><highlight class="preprocessor">#endif</highlight></codeline>
```

**Comment by michaeljones** [comment] 2015-11-08 15:15
Hi,

I suspect Doxygen is parsing this as a function instead of a macros (which I assume it is?) Breath is then telling Sphinx to parse it as a function but that is failing as it doesn't have a return type. I'm not entirely sure how best to handle this as it feels relatively unusual. It is possible to inform Doxygen of any macros that you're using and have expanded or ignored I think.

What output are you hoping to see for it?

Thanks for trying Breathe!
Michael

**Comment by kratsg** [comment] 2015-11-21 17:13
Hi @michaeljones - It is definitely a macro. I'm not entirely sure I want to see any output for it - hence my current solution to hide it from doxygen in the first place.. however, I don't expect it to crash Sphinx/Breathe if doxygen handles it just fine?

**Comment by vitaut** [comment] 2016-03-30 18:41
This is definitely a bug in Doxygen - it parses `ClassDef` as a member function.

```xml
      <memberdef kind="function" id="classJetHistsAlgo_1a6026a718a01e42ac18168acd1571734a" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type></type>
        <definition>JetHistsAlgo::ClassDef</definition>
        <argsstring>(JetHistsAlgo, 1)</argsstring>
        <name>ClassDef</name>
        <param>
          <type><ref refid="classJetHistsAlgo" kindref="compound">JetHistsAlgo</ref></type>
        </param>
        <param>
          <type>1</type>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="/home/viz/workspace/sphinx-test/test.h" line="8" column="1"/>
      </memberdef>
```
even though it is defined as a macro. Please submit a bug to Doxygen.

**Comment by melvinvermeeren** [comment] 2018-06-03 19:26
Based upon @kratsg 's recent comment in #299 I think is it safe to assume this bug has been fixed upstream, since the reproduction project here is the same as that issue.

Closing for now, if I'm wrong please comment and if possible link to upstream issue so we can track it here.

**Closed by melvinvermeeren** 2018-06-03 19:26 UTC
Labels: upstream
