### ISSUE TITLE
global namespace members are not displaying

### ISSUE THREAD

**Issue by Krishna2126** [michaeljones/breathe#415] opened 2019-02-08 05:29 UTC
functions/members in global namespace are only displaying only if same member is declared in header file.
and also in header file that function should declared without #ifdef condition.

Please check and fix if it's an issue.
else let me know how can we do it.

**Comment by melvinvermeeren** [comment] 2019-02-08 10:53
I believe the answer in #414 will also resolve this, can you check?

**Comment by melvinvermeeren** [comment] 2019-03-14 22:40
duplicate of #414

**Closed by melvinvermeeren** 2019-03-14 22:40 UTC
Labels: duplicate
