### ISSUE TITLE
breathe-fail - Derivatives not working for global members.

### ISSUE THREAD

**Issue by Krishna2126** [michaeljones/breathe#414] opened 2019-02-04 05:07 UTC
I started working with the directive of breathe.

Most of the directives are working like
Doxygenfile
Doxygenstruct
Doxygennamespace

But few directives are not working for global members(doxygenfunction, doxygenenum).
They are working for members in (namespace, struct) but not for global members.

In the attachment:

Nvmedia api.rst:
  Variable Cyclecount: working
       inside struct 
   function value: working
      inside namespace
   function TVMRVideoOFSTCreate_AllocateRing: not working
      Global

Please Let me know if I am doing anything wrong. So that I can correct

Thanks and Regards
 krishna

**Comment by Krishna2126** [comment] 2019-02-04 05:19
//Global function
    double value() {  return 2; }

**Comment by Krishna2126** [comment] 2019-02-08 05:28
if figured out that.
functions/members in global namespace are only displaying only if same member is declared in header file.
and in header file that function should not be declared with #ifdef condition.

Please check and fix if it's an issue.
else let me know how can we do it.

**Comment by melvinvermeeren** [comment] 2019-02-08 10:52
I believe this is caused by the current doxygen config, pretty sure the default is that it only extracts public things. This behaviour is probably the best, since you usually don't want local/static/private stuff in your API documentation. If you really must have this check the `EXTRACT_*` family of options: http://www.doxygen.nl/manual/config.html. This may lead to duplicate definitions however.

As for your issue with `#ifdef`, this is also a doxygen issue I had too some time ago. To fix this `ENABLE_PREPROCESSING = YES` and then make sure you define what is needed, for example POSIX 2018 with XSI you'd need `PREDEFINED = _XOPEN_SOURCE=700`.

**Comment by Krishna2126** [comment] 2019-02-12 05:38
[Doxyfile.zip](https://github.com/michaeljones/breathe/files/2854241/Doxyfile.zip)

Attaching the doxygen conf file.

Checked EXTRACT_*, still global namepace function which are not present in header are not displaying.

ENABLE_PREPROCESSING = YES, still function defined in .c and declared in header under #if condition is not displaying.
other function without #if in header are displaying.

Please check conf and let me know what am i doing wrong.

**Comment by Krishna2126** [comment] 2019-02-28 05:14
#ifdef is now working as per your guiding.

but how can work on the global members which are not present in header file.
need solution for that
i tried all the combination of EXTRACT_* still it is not taking global function which are not in header

**Comment by Krishna2126** [comment] 2019-02-28 05:15
Yes, but this seems to be also related to where the function is declared. I have EXTRACT_STATIC set to YES in my project. I made the following additions (in my project):

Header:
```int NvIspSettingsTest2();
static int NvIspSettingsTest3();```

.cpp:
```// doesn't work
static int NvIspSettingsTest()
{
    return 1;
}

// works
extern "C" int NvIspSettingsTest2()
{
    return 1;
}

// works
static int NvIspSettingsTest3()
{
    return 1;
}

// works
namespace statictest {
    static int NvIspSettingsTest4()
    {
        return 1;
    }
}```

So it seems that things fail only if
• The function is in global namespace
• And it is not declared in a header (edited)

**Comment by Krishna2126** [comment] 2019-03-04 08:36
in doxygen HTML it is displaying but not in breathe.
i think it might be a breathe issue.

**Comment by melvinvermeeren** [comment] 2019-03-14 22:28
Can you try using the `doxygenfile` directive to see if it shows up there? If it doesn't, can you check if this member has a proper doxygen comment and also if it shows up in the XML data doxygen generates?

Generally speaking you should put global variables in headers too instead of declaring them manually in the sources. You get can doxygen to also scan source files, but this will probably lead to other problems.

**Comment by Krishna2126** [comment] 2019-03-18 06:14
tried using the doxygenfile directive to see if it shows up there: that function shows in the doxygenfile directive. but when running doxygenfunction it doesnot shows.
Also checked in XML, that function is also in XML inside <file_8c.xml>.
this function should appear.
this is a genuine issue

**Comment by Krishna2126** [comment] 2019-03-25 09:49
Please check this issue it is genuine issue because function are appearing in doxygen .html but not in sphinx-breathe..

**Comment by melvinvermeeren** [comment] 2019-04-21 19:46
Hi, I had a lack of time lately but have finally had the opportunity to look at this properly.

The relevant configuration option is `breathe_implementation_filename_extensions`, quoting from current https://breathe.readthedocs.io/en/latest/directives.html#config-values

> Provides a list of the filename extensions which are considered to be implementation files. These files are ignored when the doxygenfunction directive looks for unnamespaced function names. This is to avoid the issue where the same function name appears in the doxygen XML output for a header file and implementation file because the declaration is in one and the definition is in the other. Doxygen appends the documentation from the definition to the XML for the declaration so we don’t miss any documentation information from the implementation files. The default value for this variable is:
> `breathe_implementation_filename_extensions = ['.c', '.cc', '.cpp']`

This is not (easily) fixable, the only thing I can think of is you exclude headers using this option. Then the problem changes to "doxygenfunction does not work for header-only functions". I doubt this is useful.

A potential future workaround is generating doxygen XML a second time on only source files (cpp) and adding this to breathe as a second project. Then for this project the `breathe_implementation_filename_extensions` setting would have to be different. This may require changes in breathe for per-project configuration, I am not sure.

You can also consider not including static functions in sources in the generated html documentation, which typically makes sense as including it is likely to bloat the docs.

**Comment by melvinvermeeren** [comment] 2019-08-27 13:28
Assuming resolved with answer above.

**Closed by melvinvermeeren** 2019-08-27 13:28 UTC
Labels: support
