### ISSUE TITLE
 Missing sphinx.ext.mathbase error

### ISSUE THREAD

**Issue by rmadhuraj** [michaeljones/breathe#457] opened 2019-10-22 06:25 UTC
Hi i tried building docs using sphnix,breathe , got the following error. 

**...
...
...
Running Sphinx v3.0.0+/60a3501

Exception occurred:
  File "/usr/local/lib/python3.5/site-packages/breathe/node_factory.py", line 5, in <module>
    import sphinx.ext.mathbase
ImportError: No module named 'sphinx.ext.mathbase'
The full traceback has been saved in /tmp/sphinx-err-fdcrekva.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!**

Which i reported to sphinx, where i got reply that sphinx.ext.mathbase is deprecated.
So please consider this , https://groups.google.com/forum/#!topic/sphinx-users/tMFEAw0IcHA

**Comment by melvinvermeeren** [comment] 2019-10-22 14:28
Indeed mathbase has been integrated into Sphinx core and Breathe needs to update the imports and function names where needed. I believe stable versions of Sphinx still work work Breathe.

Closing this issue as a duplicate of #451.

**Closed by melvinvermeeren** 2019-10-22 14:28 UTC
