### ISSUE TITLE
autosummary equivalent

### ISSUE THREAD

**Issue by tdegeus** [michaeljones/breathe#186] opened 2015-04-05 10:02 UTC
Hello,

I love breathe! It saves me a lot of pain in documenting my code, and it provides documentation which is highly usable. However... There is still one thing I miss: an alternative to

```
.. autosummary::
```

With Python code I use this to provide a table of contents, which gives a quick overview of the code and documentation. 

Thanks!!
Tom

**Comment by michaeljones** [comment] 2015-04-07 10:35
Hi @tdegeus,

Thanks for using breathe and for suggesting this. I think it is a good idea. I'm not quite sure how best to approach it. Can I ask how you use it? Do you do the autosummary on a separate page as a kind of index? Or do you have it on the same page as some classes, etc, and it acts as a top of the page table of contents?

Cheers,
Michael

**Comment by tdegeus** [comment] 2015-04-09 07:01
Hi Michael,

Thanks for your reply!

Personally, I use the autosummary at the top of the page as a sort of table of contents. I make use of the fact that I can choose which functions/classes/etc. to include in which order, to give the reader a quick overview of the most important user-interaction and/or the main structure of the code. In my experience, this part might be even more important to a new user than the actual documentation. 

Cheers,
Tom

PS. Unfortunately I'm not familiar with the Sphinx (autosummary) implementation, so I'm not sure that I can be of assistance with the actual implementation.

**Comment by rweickelt** [comment] 2015-04-09 07:25
Could You provide a link to an (in Your opinion) very good example? Thanks.

**Comment by melvinvermeeren** [comment] 2018-05-23 00:19
I am not 100% sure what this issue describes. But I think `breathe-apidoc` does what is requested.

If the issue is actually only an overview/index page, then the generated `genindex.html` should work.

If even that fails, then for sure #321 is what is intended. Closing for now.

**Closed by melvinvermeeren** 2018-05-23 00:19 UTC
