### ISSUE TITLE
Help Request for C# Projects

### ISSUE THREAD

**Issue by longtomjr** [michaeljones/breathe#341] opened 2017-07-15 16:45 UTC
Good day

I am having trouble understanding how to setup a repository to automaticaly generate docs using breathe, Doxygen and RTD. I am completely lost, and after a couple hours of fiddling I feel like I am missing something. 

I have read the documentation on RTD and breath and still have issues understanding exactly what I need to do to have it work.

I will be happy to contribute to the documentation of breathe to help others if I can get this to work.

Any help would be much appreciated.

Kind Regards
Longtomjr
### Extra Info:
_What I am trying to docify:_ [Project Porcupine](https://github.com/OrderOfThePorcupine/ProjectPorcupine)  

_What it is:_ A open source unity game written in C#  

_What I am having trouble with:_ Understanding how to get build instructions to RTD and setting up breathe in general; I have no issue running Doxygen on my system.

**Comment by melvinvermeeren** [comment] 2018-05-21 20:36
Hi, sorry for the delay. Do you still need help with this or have you resolved it some other way?

**Comment by melvinvermeeren** [comment] 2018-06-03 19:01
C# is currently not supported by Breathe, an extension exists for Sphinx. Refer to #249 for details.

Closing this as duplicate of 249, as I believe it is mainly about C# support.

**Closed by melvinvermeeren** 2018-06-03 19:01 UTC
Labels: support
