### ISSUE TITLE
Exception when using the C++ domain under Sphinx 1.3

### ISSUE THREAD

**Issue by EricFromCanada** [michaeljones/breathe#144] opened 2014-12-09 21:32 UTC
Sphinx 1.3 features a [rewritten C++ domain](https://bitbucket.org/birkenfeld/sphinx/pull-request/263), which now lacks the function `parse_function`, as shown below when trying to use `doxygenfunction::` on a C++ function.
```
Exception occurred:
  File "/Users/eric/Developer/projects/breathe/build/lib/breathe/renderer/rst/doxygen/domain.py", line 147, in create_function_id
    sigobj = parser.parse_function()
AttributeError: 'DefinitionParser' object has no attribute 'parse_function'
```

**Comment by vitaut** [comment] 2015-01-30 05:06
https://github.com/michaeljones/breathe/commit/db930460aa3be1751b6b68b46e2e339b0611bd90 fixes this particular error, but now there is another one:
```
  File "../breathe/renderer/rst/doxygen/domain.py", line 169, in create_class_target
    id_ = self.create_class_id(data_object)
  File "../breathe/renderer/rst/doxygen/domain.py", line 165, in create_class_id
    return sigobj.get_id()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/domains/cpp.py", line 1014, in get_id
    return _id_prefix + self.prefixedName.get_id()
AttributeError: 'ASTClass' object has no attribute 'prefixedName'
> /usr/local/lib/python2.7/dist-packages/sphinx/domains/cpp.py(1014)get_id()
-> return _id_prefix + self.prefixedName.get_id()
```

**Comment by vitaut** [comment] 2015-01-31 01:31
Looks like they completely overhauled the cpp domain in https://bitbucket.org/birkenfeld/sphinx/pull-request/263 and they seem to support a wider range of declarations now. Perhaps we should delegate the work of creating signature nodes to Sphinx now. What do you think, @michaeljones?

**Comment by michaeljones** [comment] 2015-01-31 16:09
Wow, certainly looks like an overhaul. Anything we can delegate reliably I am more than happy to do. I've forgotten the details of what is going on here. Go ahead with the changes you think are needed but if you get a sec, I'd appreciate understanding exactly what we'd be delegating. At the moment we're just asking Sphinx for the text of the 'id' we're linking to? What would be different if we delegate more?

**Comment by vitaut** [comment] 2015-01-31 17:22
I was thinking of using Sphinx to generate signature nodes (starting from `desc_signature`) for each declaration (perhaps using [describe_signature](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/domains/cpp.py#L1029) methods) and then attaching Doxygen target information and the content (documentation) to it. This way we'll have output consistent with the cpp domain directives and rely less on its internals. Hopefully this will work better in the long term. I haven't look into it in details though, this is just an idea.

**Comment by michaeljones** [comment] 2015-01-31 19:26
Hard to say without looking into it further. I suspect some of the work they are doing is already being done by doxygen but even if we're technically redoing some work it would make sense to fit as smoothly as possible as the cpp domain stuff as you suggest. Consistent output would be ideal.

Please go forth and investigate if you have the time :)

**Comment by vitaut** [comment] 2015-02-03 00:34
So here's the first stab at adding Sphinx 1.3 support and delegating more to the cpp domain: https://github.com/michaeljones/breathe/pull/167

**Comment by vitaut** [comment] 2015-02-06 01:20
Partial support for Sphinx 1.3 in `doxygenfunction` is implemented in https://github.com/michaeljones/breathe/tree/sphinx13-functions.

**Comment by vitaut** [comment] 2015-02-23 22:04
This is fixed in `master` now. The only thing that is not working with Sphinx 1.3 at the moment is the `no-link` option which is caused by Sphinx issue https://github.com/sphinx-doc/sphinx/issues/1737.

**Comment by vitaut** [comment] 2015-03-05 14:26
Support for Sphinx 1.3 is complete (#177).

**Closed by vitaut** 2015-03-05 14:26 UTC
