### ISSUE TITLE
Missed space in the parameter declaration

### ISSUE THREAD

**Issue by Grace-Li-cam** [michaeljones/breathe#656] opened 2021-03-11 03:45 UTC
Hello!

Our C++ function looks something like this:

`Object *CreateObject(std::vector<ObjectDataInterface *> object_data);`

When I run the following command to generate PDF doc, the error occurred:

`.. doxygenfunction:: CreateObject(std::vector<ObjectDataInterface *> object_data)`

It can only work if I remove the space between **ObjectDataInterface** and **\***. That is:

`.. doxygenfunction:: CreateObject(std::vector<ObjectDataInterface*> object_data)`

Is it possible to support parsing the space so that I can just copy the original name of the function instead of removing all the spaces for the functions like this? Thanks.

**Comment by jakobandersen** [comment] 2021-03-11 08:17
Do you have the error message for when the space is there? and preferably a minimum working example to reproduce the problem?

**Comment by Grace-Li-cam** [comment] 2021-03-16 10:03
error message:
```
WARNING: doxygenfunction: Unable to resolve multiple matches for function "CreateIObject" with arguments (std::vector<ObjectDataInterface*> object_data) in doxygen xml output for project "MM" from directory: ../doxygen/xml.
Potential matches:
    - Object *CreateIObject(ObjectDataInterface *object_data)
    - Object*CreateIObject(std::vector<ObjectDataInterface*> object_data)
```

working sample:

`/*!
 * @brief Creates an instance of Object with single input and it's pointed
 * by an Object pointer.
 *
 * @param[in] object_data Object data interface.
 *
 */
Object *CreateIObject (ObjectDataInterface *object_data);
/*!
 * @brief Creates an instance of Object with multiple input and it's pointed
 * by an Object pointer.
 *
 * @param[in] object_data Object data interface.
 *
 */
Object *CreateIObject(std::vector<ObjectDataInterface *> object_data);`

**Comment by jakobandersen** [comment] 2021-04-18 12:31
There was a problem with this kind of white space at some point, but it should no longer be present. I can't reproduce with the current master branch, which version are you using?
Though, I did find a different whitespace problem (see #679).

**Comment by Grace-Li-cam** [comment] 2021-06-02 07:06
I upgraded to the latest version of Breathe, the problem seems has been resolved. Thanks.

**Comment by vermeeren** [comment] 2021-09-18 02:31
Good to hear it's resolved, closing!

**Closed by vermeeren** 2021-09-18 02:31 UTC
Labels: bug, code
