### ISSUE TITLE
Showing a function in index as C instead of C++

### ISSUE THREAD

**Issue by krzychb** [michaeljones/breathe#282] opened 2016-10-24 10:32 UTC
Index generated by Sphinx is catapulting all functions described in documentation. It also indicates, in brackets after function name, if this is C or C++ function;

![image](https://cloud.githubusercontent.com/assets/12953787/19642397/56612caa-99e5-11e6-923c-696b37111fcd.png)

A function entered in documentation as:

``` c
.. c:function:: esp_err_t esp_wifi_get_ap_list (uint16_t *number, wifi_ap_list_t *ap_list)
```

Is shown a C function as expected

Another C function entered as 

``` c
.. doxygenfunction:: gpio_isr_register
```

Is shown as C++ function.

Is there a way to configure `doxygenfunction`, so on index it is showing a function as C instead of C++?

**Comment by michaeljones** [comment] 2016-11-05 16:40
Hi,

Thanks for reporting this. Sorry for the slow reponse. There isn't a way at the moment to specific C vs C++. And, yeah, Breathe kind of defaults to assuming C++.

I believe that Doxygen now ships attributes which indicate the current language in the xml so it might be possible to use that as reference to determine how the function is registered with Sphinx. I'm afraid I do not have time to investigate this but I would be happy to help if you want to try to dig into the code.

Cheers,
Michael

**Comment by krzychb** [comment] 2016-11-05 20:53
Hi Michael,

Thank you for developing and sharing Breathe!
It is a big help and it works really nice with Sphinx and Doxygen alone, as well as with Read the Docs :+1:

I have found information about language in XML file as below:
![image](https://cloud.githubusercontent.com/assets/12953787/20033400/cbbe2624-a39f-11e6-951b-02fe34d3d5dc.png)

Then I have tried to change Doxygen's option:
![image](https://cloud.githubusercontent.com/assets/12953787/20033411/271ba4c4-a3a0-11e6-8ec5-c026b309371c.png)

But the language in this file or on the index in documentation did not change,

I can try to look into the code. Where do I start?

What do you think about introducing configuration parameter like:
```
.. doxygenfunction:: gpio_isr_register
  :language: c
```

Thanks,

Krzysztof

**Comment by michaeljones** [comment] 2016-11-06 13:59
Thanks for the quick response. Actually, there is something you might try, if you haven't already. Sorry I didn't think of it before, I am very out of touch with this project.

Breathe supports the concepts of 'domains' which dictates how various things are registered with Sphinx. It might well relate to this. To control the domains that are used (C or C++) you can use the domain related configuration variables described here:

http://breathe.readthedocs.io/en/latest/directives.html#config-values

Maybe you've tried them already but I thought I'd check! Otherwise we'll dig into the code.

Thanks,
Michael

**Comment by krzychb** [comment] 2016-11-06 15:57
Hi Michael,

Thank you for support with this issue! 

I did not try this one until now. Resuts of my testing are as below:

If I do not set `breathe_domain_by_extension` (as I was doing so far), then my index looks as follows (please note some C macros and `esp_vfs_t (C++ class)` marked):

![screenshot from 2016-11-06 16-26-32](https://cloud.githubusercontent.com/assets/12953787/20039264/2d85184e-a441-11e6-8029-0271ca611a9d.png)

After setting `breathe_domain_by_extension = { "h" : "c" }`, the functions are correctly represented (as "C function"). Unfortunately all the macros (defines) and `esp_vfs_t (C++ class)` that is a _struct_, disappear from the list, 

![screenshot from 2016-11-06 16-29-19](https://cloud.githubusercontent.com/assets/12953787/20039183/07d58918-a440-11e6-9d4c-f6fa88c0a722.png)

Thanks,

Krzysztof

**Comment by michaeljones** [comment] 2016-11-06 21:07
Thanks for trying it out and the quick response! It looks like we'd be best trying to get the macros & struct registering properly with the C domain. 

I'll try to shed some more information on it but at the moment the Breathe imports and create CObjects from the C domain in Sphinx. The domain is specified in Sphinx here:

https://github.com/sphinx-doc/sphinx/blob/master/sphinx/domains/c.py

And line of code that creates them on the Breathe side is:

https://github.com/michaeljones/breathe/blob/master/breathe/renderer/sphinxrenderer.py#L45

It would be interesting to see what the `*args` being used in that call are and if they can be improved for structs or perhaps we're not calling it at all for structs. It is possible that we need a `c_classes` lookup like we have a python and cpp. In particular the cpp lookup seems to have a mapping from 'define' to 'macro', perhaps something similar is required in the C domain to make it show up properly.

I can investigate further but I'd greatly appreciate it if you have the time. I can add you as a collaborator to the project and then you can push a branch with any ideas and we can all work on it together.

**Comment by krzychb** [comment] 2016-11-19 20:31
Hi,

I am just starting with python and did not have any success exploring what you have discussed above. But I would give it another try assuming I have something simpler to start with.

In particular, I have noticed two issues with `.. doxygenfile::` directive. Maybe these issues will be more appropriate as a starter for me to resolve basing on your directions.

I will enter separate issue report, reference it back here and let's see.

**Comment by melvinvermeeren** [comment] 2018-06-02 21:48
#365 was merged for Breathe 4.8.0 and might also fix (part of) this issue, though I think the chance is small.

Just in case, could you see is the problem still exists with latest Sphinx (1.7.5) + Breathe (4.9.0)?

**Comment by krzychb** [comment] 2018-06-03 10:09
@melvinvermeeren thank you for looking into this issue.

I am currently using Sphinx (1.6.5) + Breathe (4.7.3).

After upgrade to Sphinx (1.7.5) + Breathe (4.9.0) the following issues shows up:

```
...
writing output... [  3%] api-guides/build-system                                                                 
Exception occurred:
  File "/usr/local/lib/python2.7/dist-packages/sphinx/domains/cpp.py", line 3543, in matches
    if s.identOrOp != identOrOp:
AttributeError: 'Symbol' object has no attribute 'identOrOp'
The full traceback has been saved in /tmp/sphinx-err-xau27x.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:53: recipe for target 'html' failed
make: *** [html] Error 2
```

Then I downgraded Sphinx back to (1.6.5) leaving Breathe at (4.9.0).

There are no more exceptions. I do not see any changes in the index.

![image](https://user-images.githubusercontent.com/12953787/40885454-8f18aee6-6726-11e8-8da4-ac3ad5045272.png)

Checking the internet I do not see this exception reported in context of Sphinx. Please comment how to handle it. This looks to me like a Sphinx issue Should I report it in Sphinx repository?

**Comment by melvinvermeeren** [comment] 2018-06-03 22:46
@krzychb I believe the error you get with recent Sphinx versions is indeed an issue with recent changes in the Sphinx domain. There is also a small chance it is actually Breathe using some internal Sphinx API and it's being used "incorrectly" for new versions.

If you could make an issue upstream that would be great, you may also want to refer to this one.

---

As for the issue here, I do remember reading that Sphinx's C domain is quite barebones compared to its C++ domain, but that was quite an old comment. It could still be that but it could also be that Breathe doesn't use all of Sphinx's C domain causing things to disappear.

I think Sphinx master @jakobandersen may know more about this. Subtle tag. :)

**Comment by CareF** [comment] 2018-12-07 19:49
I ran into the same issue, and everything still behave as @krzychb said. 
If I don't specify  `breathe_domain_by_extension`, everything from doxygen xml is rendered as C++, but if I set `breathe_domain_by_extension = { "h" : "c" , "c" : "c"} `, than I lost struct, micro, etc. 
@jakobandersen

**Comment by vermeeren** [comment] 2020-05-01 19:19
This might be fixed with #512, released in Breathe v4.17.0. Note that you also need Sphinx 3.x for recent Breathe versions. Could someone try and post results?

**Comment by CareF** [comment] 2020-05-01 19:29
@vermeeren  I can confirm on my side it's now correctly showing as C function. Thank yo!

**Comment by vermeeren** [comment] 2020-05-01 19:47
@CareF good to hear, closing this one then.

**Closed by vermeeren** 2020-05-01 19:47 UTC
Labels: bug, code
