### ISSUE TITLE
Adding a custom link option to doxygen directives

### ISSUE THREAD

**Issue by rowanG077** [michaeljones/breathe#362] opened 2018-01-30 12:42 UTC
Hey!

First of all thanks for creating breathe it's very nice!

Now a feature I am really missing is making a doxygen directive clickable to different page. For instance often I want to include a small description of a class and then have the extensive documentation somewhere else. Similiar to how doxygen html pages does it itself. But there is no way to make the class or function into a link.

I want to work on this myself but if you aren't agreeing with this feature I might as well not work on it. So if you are willing to merge this I will start to implement it!

If there are any question I'm happy to hear them!

**Comment by Andne** [comment] 2018-01-30 13:32
Take a look at breathe-apidoc, it can generate a .rst file for each class, which you can reference from other pages.  I've been using this to generate a page containing a list of all of my classes and then each class has documentation on its own page.

**Comment by rowanG077** [comment] 2018-01-30 14:23
Yeah I know but that is not what I mean. I have generated documentation with breathe-apidoc. Then in my design documentation I add a nutshell of my class, I want that class name to be clickable like it is in doxygen and then link to the expanded documentation. I can add links everywhere manually but that is extremely ugly. I want a custom option to make the doxygen class/functionname clickable to a link I desire.

**Comment by Andne** [comment] 2018-01-30 14:29
Is your design documentation from doxygen or written in sphinx?  Sphinx does contain support for cross-references, though it typically requires manually adding it in the rst file, that's what I've been doing with my code.  I don't know if sphinx can auto-generate links for anything that matches a given name like doxygen does.

Once you get beyond generating the content from doxygen, the rest of the parsing and rendering is powered by sphinx.  Breathe mainly just converts the doxygen xml into sphinx's internal type-tree format.

http://www.sphinx-doc.org/en/stable/domains.html#cross-referencing

**Comment by rowanG077** [comment] 2018-01-30 14:31
Both. Class and function description on the low-level are in doxygen and high level design in rst. I don't want it to automatically generate links. I simply want a new option in the directives to make the heading of the doxygen snippet a link.

**Comment by Andne** [comment] 2018-01-30 15:13
If I understand correctly you want to have one page generate a small snippet of the doxygen information (the brief description I imagine) and then have it link to the page containing the full documentation?

**Comment by rowanG077** [comment] 2018-01-30 15:19
Exactly similiar to how doxygen html works by itself. See this example: https://hlr-doxygen-docs.org/develop/doxygen/namespaceHLR_1_1Kinematics.html

This is a namespace which has links to the detailed of all classes. The class names itself is clickable. I want this feature. It doesn't have to autogenerate the links themselves. I just want to be able to add a cross reference.

**Comment by Andne** [comment] 2018-01-30 15:24
I think I like the idea, though I'm not likely to use it myself unless it can auto-generate the list.  I'm not very fond of manually maintaining lists of things like that.

**Comment by rowanG077** [comment] 2018-01-30 15:29
What I will likely do in the future is write my own version of breathe-apidoc that will extensively generate documentation in a style that is more familiar with doxygens own style. Also include the generated graphs of the html output. It will then automatically generate refs for each doxygen object and the apidoc will use it internally to allow the linking. But this has the advantage of the user also being able to easily link to apidoc from their own docs.

**Comment by rowanG077** [comment] 2018-01-31 01:07
I have been thinking some more about this an exploring the doxygen xml output. I think it would be best to create a ref option which you can keep empty and it will try to find a ref which is the same as the doxygen reference id. Eg for a a class `HLR::Kinematics::Matrix` it would be `classHLR_1_1Kinematics_1_1Matrix`. But you can still fill in a custom reference if you want.

**Comment by melvinvermeeren** [comment] 2018-05-21 19:50
If I understand this correctly, you basically want to be able to generate links to the actual documentation? Something like the index apidoc generates, but then manually, on a per-type/per-file basis?

Would something like the `outline` directive work if the output would then reference to the main docs?

http://breathe.readthedocs.io/en/latest/directives.html

**Comment by melvinvermeeren** [comment] 2018-05-22 13:41
Confirmed this is effectively a duplicate of #321. Closing this since 321 is older. Will comment some more info there in a bit.

**Closed by melvinvermeeren** 2018-05-22 13:41 UTC
Labels: suggestion

**Comment by rowanG077** [comment] 2018-05-22 13:44
Actually the other issue if newer...

**Comment by melvinvermeeren** [comment] 2018-05-22 13:45
321 was opened on 2017-02-21, this one on 2018-01-30.

**Comment by rowanG077** [comment] 2018-05-22 13:46
No it's not the same. That issue talks about generating a list of entities. This is about generating a duplicate declaration which links to the original declaration.

**Comment by melvinvermeeren** [comment] 2018-05-22 14:02
Please check what I just posted in 321, if it not at all what this issue is about I will reopen it.

**Comment by rowanG077** [comment] 2018-05-22 14:05
Let's continue discussion in that issue
