### ISSUE TITLE
type_ bug in breathe 4.0.0

### ISSUE THREAD

**Issue by michaeljones** [michaeljones/breathe#185] opened 2015-04-03 13:27 UTC
From @ela34 in #183.

Also I have installed Breathe 4.0.0 and I got an error (on Windows) when using it. I had to add a `type_` variable in `enumvalueTypeSub` function (in bold below) to get it to work. I’m not sure that this is the right thing to do, but it is not crashing anymore.

```python
class enumvalueTypeSub(supermod.enumvalueType):

    node_type = "enumvalue"
    type_ = None
    def __init__(self, prot=None, id=None, name='', initializer=None, briefdescription=None,
                 detaileddescription=None, mixedclass_=None, content_=None):
        supermod.enumvalueType.__init__(self, mixedclass_, content_)

        self.initializer = None
```

**Comment by vitaut** [comment] 2015-04-03 14:15
@ela34 What exactly error do you get? Also could you give an example that triggers the error?

**Comment by ela34** [comment] 2015-04-03 21:02
Unfortunately, I'm not able to reproduce the issue with my current setup. I will tell you if this happen again and provide as much info as I can.

**Comment by vitaut** [comment] 2015-04-03 21:20
Closing for now as I couldn't reproduce it on the latest version of Breathe. Feel free to reopen if you get this error again.

**Closed by vitaut** 2015-04-03 21:20 UTC
